### PR TITLE
Initial schematic of the first prototype

### PR DESCRIPTION
**Pull request by rnestler**
@dbrgn Can you test and verify that it works on your machine?

### CODE REVIEW

**Review by ubruhin — CHANGES_REQUESTED** [review]
Wrong EDA tool used! xD

**Comment by dbrgn** [comment]
> Wrong EDA tool used! xD

It has a library editor though 😄

**Comment by rnestler** [comment]
> It has a library editor though :smile:

Which sucks a bit though :wink:

**Comment by dbrgn** [comment]
Yeah, terribly...

**Comment by dbrgn** [comment]
Closing since we moved the repo to the gfroerli organization.

**Pull request closed without merging**
